### ISSUE TITLE
Criar modal de seleção optativas que o usuário deseja cursar

### ISSUE THREAD

**Issue by irwinschmitt** [UnBArqDsw2022-1/2022.1_G4_FluxoAgil-web#29]
![image.png](https://images.zenhubusercontent.com/5dcc58ca5697b60001449974/520841be-8b0c-4fa5-a883-f90c36fe7aa5)

**Comment by yudi-azvd** [comment]
Lembrar que esse input deve ser um botão que abre um modal. Esse modal está exemplificado no protótipo:

![image](https://user-images.githubusercontent.com/37981839/184741037-fb6ab50b-cb8f-4088-a65e-5c49ac356cf6.png)
